### ISSUE TITLE
Release new BagIt spec?

### ISSUE THREAD

**Issue by stain** [jkunze/bagitspec#20]
Hi, the current draft [draft-kunze-bagit-14](https://tools.ietf.org/html/draft-kunze-bagit-14) expired 11 months ago (http://www.ietf.org/id/draft-kunze-bagit now 404) - should we not publish a new spec? What is stopping BagIt from moving to RFC status?

There has been continued wide interest in BagIt, most recently at a [Research Data Alliance meeting on Data Archives](https://rd-alliance.org/approaches-research-data-packaging-rda-11th-plenary-bof-meeting) where all but 1 presenter used BagIt.

**Comment by acdha** [comment]
There was some pending work which needed to be done on the spec. #19 is the pull request which attempts to deal with the 1.0 blockers.

**Comment by stain** [comment]
Let me know if there something in #19 I can help with, may steal some time over Easter break.

**Comment by stain** [comment]
Closing as BagIt v1.0 was published in [draft-kunze-bagit-15](https://tools.ietf.org/html/draft-kunze-bagit-15) and subsequently updated by [draft-kunze-bagit-16](https://tools.ietf.org/html/draft-kunze-bagit-16)

**Comment by stain** [comment]
Or was it? https://github.com/jkunze/bagitspec/pull/19 is still open..

**Comment by acdha** [comment]
@stain It's still working through the final steps of the approval process. You can see exactly where it's at in https://datatracker.ietf.org/doc/conflict-review-kunze-bagit/
